name: Docker Image CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint (critical errors only)
        run: |
          # E9, F63, F7, F82 are the most critical (syntax errors, undefined names)
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Lint (report, non-blocking)
        run: |
          # Non-blocking style report for visibility
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Syntax check
        run: |
          python -m compileall -q .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: discord-chess-bot:ci
